controllers:
    resource: ../src/Controller/
    type: attribute

login:
    path: /{_locale}/login
    controller: App\Controller\SecurityController::ConnexionController
    requirements:
        _locale: 'en|fr'
    
app_homepage:
    path: /
    controller: Symfony\Component\HttpFoundation\RedirectResponse
    defaults:
        path: /en
    methods: GET
